### ISSUE TITLE
"Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Logging reversed:"

### ISSUE THREAD

**Issue by asajigithub** [mgm3746/garbagecat#138] opened 2020-07-15 02:53 UTC
Unable to Parse the gc log
Command
~~~
java -jar garbagecat-3.0.5-SNAPSHOT.jar -p <gc.log>
~~~

CMD Line Stack
~~~
Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Logging reversed: 
2020-07-14T09:14:56.049-0400: 5488.287: [GC pause (G1 Evacuation Pause) (young), 0.0741698 secs][Eden: 1133.0M(1133.0M)->0.0B(1138.0M) Survivors: 97280.0K->92160.0K Heap: 1549.5M(2048.0M)->383.1M(2048.0M)] [Times: user=0.35 sys=0.00, real=0.07 secs]
2020-07-14T09:15:03.899-0400: 5359.504: [GC pause (G1 Evacuation Pause) (young), 0.0660353 secs][Eden: 1151.0M(1151.0M)->0.0B(1142.0M) Survivors: 78848.0K->88064.0K Heap: 1554.5M(2048.0M)->378.2M(2048.0M)] [Times: user=0.26 sys=0.00, real=0.06 secs]
	at org.eclipselabs.garbagecat.service.GcManager.store(GcManager.java:468)
	at org.eclipselabs.garbagecat.Main.main(Main.java:153)
~~~

Attaching the gc log
[sg-prod-uni-fe-GC.log_prd8077.gz](https://github.com/mgm3746/garbagecat/files/4922572/sg-prod-uni-fe-GC.log_prd8077.gz)

**Comment by mgm3746** [comment] 2020-07-15 21:19
It looks like the logging order got mixed up for some reason. The -r option reorders the logging before parsing:
java -jar garbagecat-3.0.5-SNAPSHOT.jar -p -t 50 -r ~/Downloads/sg-prod-uni-fe-GC.log_prd8077 

The reordering option was adding for when logging is managed by some centralized logging aggregator. Sometimes these aggregators mix the order of the logging for some reason (probably a bug in the logging aggregator).

It can also happen when the logging from multiple JVMs is logged to a single file.

How was this logging created? Is a logging aggregator involved? Anything special about the environment or how the gc logging is logged?

**Comment by mgm3746** [comment] 2020-10-31 19:25
I'm going to close this out as not reproducible. It doesn't look like the JVM is under stress, which can cause odd logging in JDK8. Please re-open if you experience this again or have any new information.

**Closed by mgm3746** 2020-10-31 19:25 UTC
